name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:
        CI: true
        DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
        ORDER_HANDLER_NUMBER: ${{ secrets.ORDER_HANDLER_NUMBER }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SES_EMAIL: ${{ secrets.AWS_SES_EMAIL }}
        ORDER_HANDLER_EMAIL: ${{ secrets.ORDER_HANDLER_EMAIL }}